spring.application.name=gRPC-Test


spring.grpc.server.port=9090
spring.grpc.server.reflection.enabled=true


spring.datasource.url = jdbc:postgresql://localhost:5432/StockDB
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect